apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mediamtx
  name: mediamtx
spec:
  ports:
  - name: "8554"
    port: 8554
    targetPort: 8554
  - name: "8888"
    port: 8888
    targetPort: 8888
  - name: "1935"
    port: 1935
    targetPort: 1935
  selector:
    io.kompose.service: mediamtx
status:
  loadBalancer: {}
