apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "fastapi-app.fullname" . }}-deployer-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "fastapi-app.fullname" . }}
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]