apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fastapi-app.fullname" . }}-deployer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "fastapi-app.fullname" . }}
    release: {{ .Release.Name }}
