apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: rtsp
      port: {{ .Values.service.ports.rtsp }}
      targetPort: {{ .Values.service.ports.rtsp }}
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
