replicaCount: 1

image:
  repository: cr.yandex/crpa91sr9tr2i9j9gpba/stream-processor-cuda
  pullPolicy: Always
  tag: latest


command: ["/bin/sh"]
args: 
  - "-c"
  - "python3.10 read_frames.py"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: "2"
    memory: "4Gi"
    nvidia.com/gpu: 1
  limits:
    cpu: "2"
    memory: "4Gi"
    nvidia.com/gpu: 1

env:
  - name: OMP_NUM_THREADS
    value: "2"
  - name: MKL_NUM_THREADS
    value: "2"
  - name: NUMEXPR_NUM_THREADS
    value: "2"
  - name: OPENBLAS_NUM_THREADS
    value: "2"
  - name: VECLIB_MAXIMUM_THREADS
    value: "2"
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: RTSP_IN
    value: "rtsp://mediamtx-svc:8554/mediamtx/stream3"
  - name: RTSP_OUT
    value: "rtsp://mediamtx-svc:8554/mediamtx/newstream1"

