# Default values for mediamtx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

image:
  repository: bluenviron/mediamtx
  tag: latest-ffmpeg

service:
  type: ClusterIP
  ports:
    rtsp: 8554
    http: 8888

persistence:
  enabled: true
  storageClass: yc-network-hdd  # Сетевой HDD
  size: 10Gi
  mountPath: /media/videos

# ingress:
#   enabled: true
#   className: nginx
#   annotations:
#     yandex.cloud/load-balancer-type: "external"
#     yandex.cloud/subnet-id: "e2lafcbevjq0o2rn6qdn"  # Ваш subnet-id
#   hosts:
#     - host: ""
#       paths:
#         - path: /mediamtx(/|$)(.*)
#           pathType: ImplementationSpecific
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /$2
#     nginx.ingress.kubernetes.io/use-regex: "true"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    yandex.cloud/load-balancer-type: "external"
    yandex.cloud/subnet-id: "e2lafcbevjq0o2rn6qdn"  # Ваш subnet-id
  hosts:
    - host: ""  # Доступ по IP (или укажите домен)
      paths:
        - path: /mediamtx
          pathType: Prefix
  tls: []


env:  # Environment variables (e.g., DB connection)
  - name: RTSP_PORT
    value: "8554"
  - name: HLS_PORT
    value: "8888"
  - name: MTX_PROTOCOLS
    value: tcp
